export const uiText = {
  en: {
    appTitle: 'SIS University Platform',
    appSubtitle: 'Real Full-Stack Student Information System',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    settings: 'Settings',
    systemStatus: 'System Status',
    connected: 'Connected',
    disconnected: 'Disconnected',
    checking: 'Checking...',
    refresh: 'Refresh',
    checkNow: 'Check Now',
    lastCheck: 'Last Check',
    apiBase: 'API Base',
    environment: 'Environment',
    database: 'Database',
    loadedRoutes: 'Loaded Routes',
    missingRoutes: 'Missing Routes',
    sectionModules: 'Modules',
    moduleData: 'Module Data',
    moduleStats: 'Module Statistics',
    createRecord: 'Create Record',
    payloadHint: 'JSON payload',
    submit: 'Submit',
    back: 'Back',
    noData: 'No records available yet.',
    requestFailed: 'Request failed',
    saveSuccess: 'Record created successfully',
    saveFailed: 'Create request failed',
    totalRecords: 'Total Records',
    totalModules: 'Total Modules',
    categories: 'Categories',
    notFound: 'Page not found',
    backToDashboard: 'Back to Dashboard',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    uiDirection: 'UI Direction',
    ltr: 'LTR',
    rtl: 'RTL',
    experience: 'Experience',
    experienceDesc: 'Modern responsive interface with SCSS design system, multilingual UX, and direct backend integration.'
  },
  ar: {
    appTitle: 'منصة SIS الجامعية',
    appSubtitle: 'نظام معلومات طلابي متكامل Full-Stack',
    dashboard: 'لوحة التحكم',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    systemStatus: 'حالة النظام',
    connected: 'متصل',
    disconnected: 'غير متصل',
    checking: 'جاري الفحص...',
    refresh: 'تحديث',
    checkNow: 'فحص الآن',
    lastCheck: 'آخر فحص',
    apiBase: 'مسار API',
    environment: 'البيئة',
    database: 'قاعدة البيانات',
    loadedRoutes: 'المسارات المتاحة',
    missingRoutes: 'المسارات غير المتاحة',
    sectionModules: 'الوحدات',
    moduleData: 'بيانات الوحدة',
    moduleStats: 'إحصائيات الوحدة',
    createRecord: 'إضافة سجل',
    payloadHint: 'بيانات JSON',
    submit: 'إرسال',
    back: 'رجوع',
    noData: 'لا توجد سجلات حالياً.',
    requestFailed: 'فشل الطلب',
    saveSuccess: 'تم إنشاء السجل بنجاح',
    saveFailed: 'فشل إنشاء السجل',
    totalRecords: 'إجمالي السجلات',
    totalModules: 'إجمالي الوحدات',
    categories: 'الأقسام',
    notFound: 'الصفحة غير موجودة',
    backToDashboard: 'العودة للوحة التحكم',
    language: 'اللغة',
    theme: 'المظهر',
    light: 'فاتح',
    dark: 'داكن',
    uiDirection: 'اتجاه الواجهة',
    ltr: 'يسار إلى يمين',
    rtl: 'يمين إلى يسار',
    experience: 'التجربة',
    experienceDesc: 'واجهة حديثة ومتجاوبة باستخدام SCSS مع تجربة متعددة اللغات وربط مباشر مع الباك إند.'
  }
};

export const getText = (language) => uiText[language] || uiText.en;
